spring:
  application:
    name: cloud-register-center
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka
---
spring:
  profiles: peer1
server:
  port: 9000
eureka:
  instance:
    appname: peer1
  client:
    service-url:
     defaultZone: http://peer2:9001/eureka/,http://peer3:9002/eureka/
---
spring:
  profiles: peer2
server:
  port: 9001
eureka:
  instance:
    appname: peer2
  client:
    service-url:
     defaultZone: http://eureka:eureka@peer3:9002/eureka/,http://eureka:eureka@peer1:9000/eureka/
---
spring:
  profiles: peer3
server:
  port: 9002
eureka:
  instance:
    appname: peer3
  client:
    service-url:
     defaultZone: http://eureka:eureka@peer1:9000/eureka/,http://eureka:eureka@peer2:9001/eureka/
---
spring:
  profiles: dev
server:
  port: 9004
eureka:
  instance:
    appname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9004/eureka/
#移除eureka的保护机制
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000