spring:
  application:
    name: cloud-user-microservice
server:
  port: 9010
---
eureka:
  instance:
    appname: cloud-user-microservice
  client:
    service-url:
     defaultZone: http://peer1:9000/eureka/,http://peer2:9001/eureka/,http://peer3:9002/eureka/
spring:
  profiles: ha
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:9004/eureka
  instance:
    appname: cloud-user-microservice
